export const ADD_OBJETIVO_PALANCA_ERROR = 'ADD_OBJETIVO_PALANCA_ERROR';
export const ADD_OBJETIVO_PALANCA_LOADING = 'ADD_OBJETIVO_PALANCA_LOADING';
export const ADD_OBJETIVO_PALANCA_SUCCESS  = 'ADD_OBJETIVO_PALANCA_SUCCESS ';

export const EDIT_OBJETIVO_PALANCA_ERROR = 'EDIT_OBJETIVO_PALANCA_ERROR';
export const EDIT_OBJETIVO_PALANCA_LOADING = 'EDIT_OBJETIVO_PALANCA_LOADING';
export const EDIT_OBJETIVO_PALANCA_SUCCESS = 'EDIT_OBJETIVO_PALANCA_SUCCESS ';

export const FETCH_OBJETIVO_PALANCA_ERROR = 'FETCH_OBJETIVO_PALANCA_ERROR';
export const FETCH_OBJETIVO_PALANCA_LOADING = 'FETCH_OBJETIVO_PALANCA_LOADING';
export const FETCH_OBJETIVO_PALANCA_SUCCESS  = 'FETCH_OBJETIVO_PALANCA_SUCCESS ';

export const DELETE_OBJETIVO_PALANCA_ERROR = 'DELETE_OBJETIVO_PALANCA_ERROR';
export const DELETE_OBJETIVO_PALANCA_LOADING = 'DELETE_OBJETIVO_PALANCA_LOADING';
export const DELETE_OBJETIVO_PALANCA_SUCCESS  = 'DELETE_OBJETIVO_PALANCA_SUCCESS ';